#
# Simple Makefile to build the demo programs
#
# Eleanor Birrell
# Pomona College
# January 22, 2020
#
CC = gcc

all:	demo00

demo00: demo00.c
	$(CC) -o demo00 demo00.c 

clean:
	rm -rf demo00
	rm -rf *~
